#!/bin/sh

file="$1"
email=''
server='srv-store1'

# Uncomment if you don't already know your server. I recommend running this command once to make things faster once and for all.
server=$(curl https://apiv2.gofile.io/getServer | jq .data.server | sed 's/["]//g')
message=$(curl -F email="$email" -F file=@"$file" https://"$server".gofile.io/uploadFile)
code=$(echo $message | jq .data.code | sed 's/["]//g')
url="https://gofile.io/d/$code"
if [ $XDG_SESSION_TYPE='wayland' ]; then
  wl-copy "$url"
else
  xclip "$url"
fi
notify-send "$file - $email" "$url" -i (pwd)/$file
