#!/bin/sh

# use it like that 'wofer /path/to/extensions/fzf'

fzf --layout=reverse --height=100% --min-height=900 --print-query\
    -i +m\
    --bind=ctrl-l:accept\
    --bind="tab:execute(echo '?')+abort"\
    --bind="}:execute(echo ZZ)+abort"\
    --bind="ctrl-h:execute(echo ..)+abort"\
    --bind="\:execute(echo :h)+abort"\
    --preview='lsd {}'\
    --preview-window=right:50%:sharp\
    --color=fg:#8ab3cd,hl:#ebcb8b\
    --color=preview-fg:#d8dee9,border:#4c566a\
    --color=fg+:#caafc5,bg+:#3b4252,hl+:#8ab3cd\
    --color=info:#eacb8a,prompt:#bf6069,pointer:#b48dac\
    --color=marker:#a3be8b,spinner:#b48dac,header:#d99f8c

