#! /bin/sh

sxhkd &

##bspc monitor -d TERM MUSIC WEB FILES DEV
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config focus_follows_pointer true
bspc config border_width         3
bspc config border_radius         12
bspc config window_gap           15
bspc config focused_border_color "#36424d"
bspc config normal_border_color "#182022"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
sh .fehbg
xrdb -merge ~/.config/bspwm/x
~/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &
picom &

