source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
colorscheme kakoune-plain
plug "zkmrgirish/kakoune-plain" theme
plug "andreyorst/kaktree" config %{
        hook global WinSetOption filetype=kaktree %{
                remove-highlighter buffer/numbers
                remove-highlighter buffer/matching
                remove-highlighter buffer/wrap
                remove-highlighter buffer/show-whitespaces
        }
            kaktree-enable
}
set global ui_options ncurses_assistant=none
